apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort    # easier for Minikube; change to LoadBalancer in cloud
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
